## 3.1.

In [2]:
import numpy as np

c = np.array([[1, 0, 0, 0, 0, 0, 0]])
W = np.random.randn(7, 3)
print(W)
h = c @ W
print(h)

[[-0.97469954 -0.91540244  1.08640145]
 [ 0.52752251  2.41655744 -1.55914714]
 [-2.85632869 -1.06769199 -0.49370025]
 [ 0.93471156 -1.27753296 -1.44140749]
 [-1.97612585 -1.43337347 -0.10312917]
 [-2.08970765  0.32251255  0.12549656]
 [ 0.02141437  0.04944958 -0.99916695]]
[[-0.97469954 -0.91540244  1.08640145]]


In [6]:
import numpy as np

class MatMul():
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None
    
    
    def forward(self, x):
        W = self.params[0]
        self.x = x
        out = x @ W
        return out
    
    
    def backward(self, dout):
        W,  = self.params
        dx = dout @ W.T
        dW = self.x.T @ dout
        self.grads[0][:] = dW
        return dx
    
C = np.array([1, 0, 0, 0, 0, 0, 0])
W = np.random.randn(7, 3)
layer = MatMul(W)
h = layer.forward(C)

print(W)
print(h)

[[ 0.11223176  0.55746567  0.53828026]
 [-1.27609581  1.13860589  0.89705676]
 [-1.69177519 -0.35153665  1.82963954]
 [ 0.6695847   0.21658624  0.18038846]
 [-0.1623058   0.53770619 -0.11069966]
 [-1.75581238  0.1428787  -0.34371074]
 [-0.38509651  1.65000981 -0.57113696]]
[0.11223176 0.55746567 0.53828026]


## 3.2. 단순한 word2vec

In [9]:
class MatMul():
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        
        self.x = None
        
    def forward(self, x):
        W, = self.params
        self.x = x
        out = x @ W
        return out
    
    def backward(self, dout):
        x = self.x
        W, = self.params
        
        dW = x.T @ dout
        self.grads[0][:] = dW
        
        dx = dout @ W.T
        return dx
    
c0 = np.array([[1, 0, 0, 0, 0, 0, 0]])
c1 = np.array([[0, 1, 0, 0, 0, 0, 0]])

W_in = np.random.randn(7, 3)
W_out = np.random.randn(3, 7)

in_layer0 = MatMul(W_in)
in_layer1 = MatMul(W_in)
out_layer = MatMul(W_out)

h0 = in_layer0.forward(c0)
h1 = in_layer0.forward(c1)
h = 0.5 * (h0 + h1)
s = out_layer.forward(h)

print(s)

[[-0.12915369 -0.67828126  0.91318618  0.48959303 -2.07165867 -0.82535997
   0.98388772]]


In [5]:
from common.util import preprocess, create_contexts_target, convert_one_hot

corpus, word_to_id, id_to_word = preprocess("You say goodbye and I say hello.")

contexts, target = create_contexts_target(corpus)

In [6]:
vocab_size = len(word_to_id)
convert_one_hot(contexts, vocab_size).shape, convert_one_hot(target, vocab_size).shape

((6, 2, 7), (6, 7))

## 3.4. CBOW 모델 구현